export const SET_LOGIN = "SET_LOGIN"
export const ADD_REGISTER = "ADD_REGISTER"
export const FETCH_VENUE = "FETCH_VENUE"
export const ADD_ITEM = "ADD_ITEM"
export const DELETE = "DELETE"
export const EDIT = "EDIT"